# -*- coding: utf-8 -*-
"""3ST_Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RDmh-0NE4ZIsJsSmOhuSvTgL1yGh0qom

# Test de los Tres Estados
"""

options(warn=-1)

# data
ibmdata = read.csv("IBM.csv",sep=",") # read csv 
ibmdata$Date <- as.Date(ibmdata$Date,format="%Y-%m-%d") # date formatting
ln_diff=c(NA,diff(log(ibmdata$Close)))
ibmdata$d_ln_close=ln_diff #creamos la variable d_ln_y (1st row, NA)
y=ibmdata$d_ln_close[2:nrow(ibmdata)]

maximo=800
# definimos LS (tarda bastante, por lo que puede cambiarse maximo por otro).
Sys.time()
mu=numeric()
for (W in 1:maximo){
  y=ibmdata$d_ln_close[1:W]
  v=order(y)
  LS=numeric()
  for (N in 1:length(y)){
    vkn=v[v<N]
    vaux=numeric()
    for (K in 1:N-2){
      vaux[K]=vkn[K+1]-vkn[K]
    }
    LS[N]=max(vaux)
  }
  LS=LS[3:length(LS)]
  p=10
  hat_LS=(1/length(LS))*sum(LS[seq(1,length(LS),p)])
  sigma=sqrt(1/length(LS)*(sum((LS[seq(1,length(LS),p)]-hat_LS)^2)))
  mu[W]=log(1+sigma)/log(length(LS))}
Sys.time()
plot(mu, type="l")

arma = as.numeric(read.csv("arma11.csv",sep=",",header=FALSE)[,1]) # read csv 
garc = as.numeric(read.csv("garc11.csv",sep=",",header=FALSE)[,1]) # read csv 
egar = as.numeric(read.csv("egar21.csv",sep=",",header=FALSE)[,1]) # read csv

y=arma

maximo=800
# definimos LS (tarda bastante, por lo que puede cambiarse maximo por otro).
Sys.time()
mu=numeric()
for (W in 1:maximo){
  y=ibmdata$d_ln_close[1:W]
  v=order(y)
  LS=numeric()
  for (N in 1:length(y)){
    vkn=v[v<N]
    vaux=numeric()
    for (K in 1:N-2){
      vaux[K]=vkn[K+1]-vkn[K]
    }
    LS[N]=max(vaux)
  }
  LS=LS[3:length(LS)]
  p=10
  hat_LS=(1/length(LS))*sum(LS[seq(1,length(LS),p)])
  sigma=sqrt(1/length(LS)*(sum((LS[seq(1,length(LS),p)]-hat_LS)^2)))
  mu[W]=log(1+sigma)/log(length(LS))}
Sys.time()
plot(mu, type="l")

LS

y=garc

maximo=800
# definimos LS (tarda bastante, por lo que puede cambiarse maximo por otro).
Sys.time()
mu=numeric()
for (W in 1:maximo){
  y=ibmdata$d_ln_close[1:W]
  v=order(y)
  LS=numeric()
  for (N in 1:length(y)){
    vkn=v[v<N]
    vaux=numeric()
    for (K in 1:N-2){
      vaux[K]=vkn[K+1]-vkn[K]
    }
    LS[N]=max(vaux)
  }
  LS=LS[3:length(LS)]
  p=10
  hat_LS=(1/length(LS))*sum(LS[seq(1,length(LS),p)])
  sigma=sqrt(1/length(LS)*(sum((LS[seq(1,length(LS),p)]-hat_LS)^2)))
  mu[W]=log(1+sigma)/log(length(LS))}
Sys.time()
plot(mu, type="l")

y=egar

maximo=800
# definimos LS (tarda bastante, por lo que puede cambiarse maximo por otro).
Sys.time()
mu=numeric()
for (W in 1:maximo){
  y=ibmdata$d_ln_close[1:W]
  v=order(y)
  LS=numeric()
  for (N in 1:length(y)){
    vkn=v[v<N]
    vaux=numeric()
    for (K in 1:N-2){
      vaux[K]=vkn[K+1]-vkn[K]
    }
    LS[N]=max(vaux)
  }
  LS=LS[3:length(LS)]
  p=10
  hat_LS=(1/length(LS))*sum(LS[seq(1,length(LS),p)])
  sigma=sqrt(1/length(LS)*(sum((LS[seq(1,length(LS),p)]-hat_LS)^2)))
  mu[W]=log(1+sigma)/log(length(LS))}
Sys.time()
plot(mu, type="l")

## funciones

lsparcial=function(LS,p,N0,n){
  nm=numeric()
  for (i in 1:p+1){
    nm[i]=LS[(i-1)*N0+n]
  }
  nm
}

LS_hat=function(n,LS,p,N0,N){
  zz=lsparcial(LS,p,N0,n)
  suma=sum(zz[2:length(zz)])
  valor=suma/N
  valor
}

sigmaparcial=function(p,N0,n,LS,N){
  nm=numeric()
  hhh=LS_hat(n,LS,p,N0,N0)
  for (i in 1:p+1){
    nm[i]=(LS[(i-1)*N0+n]-hhh)^2
  }
  sumasumisima=sum(nm[2:length(nm)])
  sumasumisima
}

sigma=function(p,N0,n,LS,N){
  sqrt((1/N)*sigmaparcial(p,N0,n,LS,N))
}

mu=function(p,N0,n,LS,N){
  log(1+sigma(p,N0,n,LS,N))/log(N)
}







# second approach 
y=ibmdata$d_ln_close[2:nrow(ibmdata)]
v=order(y)
LS=numeric()
  for (N in 1:length(y)){
    vkn=v[v<N]
    vaux=numeric()
    for (K in 1:N-2){
      vaux[K]=vkn[K+1]-vkn[K]
    }
    LS[N]=max(vaux)}
LS=LS[3:length(LS)]
n=50
N=length(LS)
p=10
N0=floor((N-n)/p)
N1=700
p=10
LS=LS
N=length(LS)
results=numeric()
for (i in 3:(length(LS)-1000)){
  N0=floor((N-i)/p)
  results[i]=mu(p,N0,i,LS,N)
}
plot(results,type="l",ylim=c(0.55,0.7))

y=arma

v=order(y)
LS=numeric()
  for (N in 1:length(y)){
    vkn=v[v<N]
    vaux=numeric()
    for (K in 1:N-2){
      vaux[K]=vkn[K+1]-vkn[K]
    }
    LS[N]=max(vaux)}
LS=LS[3:length(LS)]
n=50
N=length(LS)
p=10
N0=floor((N-n)/p)
N1=700
p=10
LS=LS
N=length(LS)
results=numeric()
for (i in 3:(length(LS)-1000)){
  N0=floor((N-i)/p)
  results[i]=mu(p,N0,i,LS,N)
}
plot(results,type="l",ylim=c(0.55,0.7))

y=garc

v=order(y)
LS=numeric()
  for (N in 1:length(y)){
    vkn=v[v<N]
    vaux=numeric()
    for (K in 1:N-2){
      vaux[K]=vkn[K+1]-vkn[K]
    }
    LS[N]=max(vaux)}
LS=LS[3:length(LS)]
n=50
N=length(LS)
p=10
N0=floor((N-n)/p)
N1=700
p=10
LS=LS
N=length(LS)
results=numeric()
for (i in 3:(length(LS)-1000)){
  N0=floor((N-i)/p)
  results[i]=mu(p,N0,i,LS,N)
}
plot(results,type="l",ylim=c(0.55,0.7))

y=egar

v=order(y)
LS=numeric()
  for (N in 1:length(y)){
    vkn=v[v<N]
    vaux=numeric()
    for (K in 1:N-2){
      vaux[K]=vkn[K+1]-vkn[K]
    }
    LS[N]=max(vaux)}
LS=LS[3:length(LS)]
n=50
N=length(LS)
p=10
N0=floor((N-n)/p)
N1=700
p=10
LS=LS
N=length(LS)
results=numeric()
for (i in 3:(length(LS)-1000)){
  N0=floor((N-i)/p)
  results[i]=mu(p,N0,i,LS,N)
}
plot(results,type="l",ylim=c(0.55,0.7))

