# -*- coding: utf-8 -*-
"""graf_recurrencia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nTRZQ7OjctFSQ_8kGVTTXFVAyb9MdOLn
"""

import seaborn as sns
import pandas as pd
from matplotlib import pyplot
import numpy as np
import math as mt
from PIL import Image

a=pd.read_csv("IBM.csv") # debe subirse IBM.csv

d_ln_a=[]
a0=a.Close[0]
for i in a.Close[1:]:
  d_ln_a.append(mt.log(i)-mt.log(a0))
  a0=i

a4_dims = (20, 6)
fig, ax = pyplot.subplots(figsize=a4_dims)
sns.lineplot(range(len(d_ln_a)),d_ln_a)

x=d_ln_a

arr=[]
eps=0.005
for i in range(len(x)):
  for j in range(len(x)):
    if abs(x[i]-x[j])<eps:
      arr.append(0)
    else:
      arr.append(255)
arr=np.array(arr)
arr=arr.astype(np.uint8)

arr.resize((len(x),len(x)))

im = Image.fromarray(arr,mode="L")
im.show()

im.resize((600,600))



