# -*- coding: utf-8 -*-
"""TFG_matemáticas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X3CjvW2J2UDByIl__xd48oDYboMA2ouQ

## TFG Matemáticas

## 0 Import Libraries & Data

Librerías utilizadas:
* ggplot2

Primero, importamos los datos sobre los que queremos trabajar. En nuestro caso, y dado lo adeucado de este tipo de análisis sobre series financieras, he decido utilizar el histórico (desde 1960) hasta hoy (2020) diario del valor de la acción de IBM en la bolsa de Nueva York (N

_A día 18 de mayo del 2020, tarda en:_
- _instalar paquetes: $\approx 2\mathrm{m}\,8\mathrm{s}$_
- _cargar el resto del cuaderno: prácticamente nada
"""

# not-installed libs 
install.packages("dygraphs")
install.packages("fNonlinear")
install.packages("tseries")
install.packages("forecast")
install.packages("rugarch")

# libs
library(ggplot2)
library(dygraphs)
library(lubridate)
library(xts)          # To make the convertion data-frame / xts format
library(tidyverse)
library(htmlwidgets)
library(fNonlinear)
library(tseries)
library(forecast)
library(rugarch)

ibmdata = read.csv("IBM.csv",sep=",") # read csv
ibmdata$Date <- as.Date(ibmdata$Date,format="%Y-%m-%d") # date formatting

head(ibmdata)

dd <- xts(x = ibmdata$Close, order.by = ibmdata$Date)

p <- dygraph(dd) %>%
  dyOptions(labelsUTC = TRUE, fillGraph=TRUE, fillAlpha=0.2, drawGrid = FALSE, colors="#0000FF") %>%
  dyRangeSelector() %>%
  dyCrosshair(direction = "vertical") %>%
  dyHighlight(highlightCircleSize = 5, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = FALSE)  %>%
  dyRoller(rollPeriod = 1)

# saveWidget(p,"ibm_stocks.html") # guardamos el gráfico interactivo. Aquí abrimos
# una pequeña representación: (que también guardamos)

p <- ggplot(ibmdata, aes(x=Date, y=Close)) +
  geom_line() + 
  xlab("")
p
ggsave(file="ibm_serie.eps")

"""### 0.1 Estadísticas Descriptivas de la serie original

Media, Mediana, DT, Mínimo, Máximo, Asimetría, Curtosis, Jarque-Bera y N
"""

y=ibmdata$Close

mean(y)

median(y)

sd(y)

min(y)

max(y)

skewness=function(x) {
m3=mean((x-mean(x))^3)
skew=m3/(sd(x)^3)
skew}
skewness(y)

kurtosis=function(x) {
m4=mean((x-mean(x))^4)
kurt=m4/(sd(x)^4)-3 
kurt}
kurtosis(y)

jarque.bera.test(y)

length(y)

serie_original=y
plot=qplot(serie_original, geom="histogram") 
plot
ggsave(plot,file="hist_original.eps")

"""### 0.2 Creación d_ln_y_t (y estadísticas descriptivas)

Se crea la variable $z_t = \nabla\ln (y_t)$
"""

ln_diff=c(NA,diff(log(ibmdata$Close)))
ibmdata$d_ln_close=ln_diff #creamos la variable d_ln_y (1st row, NA)

head(ibmdata)

y=ibmdata$d_ln_close

y=y[2:length(y)]
red=ibmdata[2:nrow(ibmdata),]

p <- ggplot(red, aes(x=Date, y=d_ln_close)) +
  geom_line() + 
  xlab("")
p
ggsave(file="ibm_retornos.eps")

mean(y)

median(y)

sd(y)

min(y)

max(y)

skewness=function(x) {
m3=mean((x-mean(x))^3)
skew=m3/(sd(x)^3)
skew}
skewness(y)

kurtosis=function(x) {
m4=mean((x-mean(x))^4)
kurt=m4/(sd(x)^4)-3 
kurt}
kurtosis(y)

jarque.bera.test(y)

length(y)

retornos=y
plot=qplot(retornos, geom="histogram") 
plot
ggsave(plot,file="hist_retornos.eps")

qqnorm(y)
qqline(y, col = "blue")
ggsave(plot,file="qqplot_retornos.eps")

"""## 1 Modelización de la serie

### 1.1 Modelización ARMA
"""

plot(acf(y,plot=F)[1:35])

pacf(y)

"""**ARMA(0,0)**"""

auto.arima(y,ic="bic")

arma00=arima(y,c(0,0,0))

bic=AIC(arma00,k=log(length(y)))
bic

residuos_arma00=residuals(arma00)

plot(acf(residuos_arma00,plot=F)[1:35])

pacf(residuos_arma00)

"""**ARMA(1,1)**"""

arma11=arima(y,c(1,0,1))

bic=AIC(arma11,k = log(length(y)))
bic

residuos_arma11=residuals(arma11)

plot(acf(residuos_arma11,plot=F)[1:35])

pacf(residuos_arma11)

"""#### Estadísticas Descriptivas de los residuos del ARMA(1,1)

Media, Mediana, DT, Mínimo, Máximo, Asimetría, Curtosis, Jarque-Bera y N
"""

y=residuos_arma11

mean(y)

median(y)

sd(y)

min(y)

max(y)

skewness=function(x) {
m3=mean((x-mean(x))^3)
skew=m3/(sd(x)^3)
skew}
skewness(y)

kurtosis=function(x) {
m4=mean((x-mean(x))^4)
kurt=m4/(sd(x)^4)-3 
kurt}
kurtosis(y)

jarque.bera.test(y)

length(y)

residuos_arma11=y
plot=qplot(residuos_arma11, geom="histogram") 
plot
ggsave(plot,file="hist_arma11.eps")

qqnorm(y)
qqline(y, col = "blue")
ggsave(plot,file="qqplot_arma11.eps")

plot(y)

"""### 1.2 Modelización GARCH

**GARCH(1,1)**
"""

garch11=garch(y,c(1,1))

bic=AIC(garch11,k = log(length(y)))
bic

#for (i in 0:3){
#  for (j in 1:3){
#    mod <- garch(y,c(i,j))
#    bic=AIC(mod,k = log(length(y)))
#    print(c('----->',i,j,":",bic))
#  }
#}

residuos_garch11=residuals(garch11)[2:length(residuos_garch11)]

"""#### Estadísticas Descriptivas de GARCH(1,1)

Media, Mediana, DT, Mínimo, Máximo, Asimetría, Curtosis, Jarque-Bera y N
"""

y=residuos_garch11

mean(y)

median(y)

sd(y)

min(y)

max(y)

skewness=function(x) {
m3=mean((x-mean(x))^3)
skew=m3/(sd(x)^3)
skew}
skewness(y)

kurtosis=function(x) {
m4=mean((x-mean(x))^4)
kurt=m4/(sd(x)^4)-3 
kurt}
kurtosis(y)

jarque.bera.test(y)

length(y)

serie_garch11=y
plot=qplot(serie_garch11, geom="histogram") 
plot
ggsave(plot,file="hist_garch11.eps")

qqnorm(y)
qqline(y, col = "blue")
ggsave(plot,file="qqplot_garch11.eps")

plot(y)

"""### 1.3 Modelización EARCH"""

spec = ugarchspec(variance.model = list(model = "eGARCH", garchOrder = c(1,1)))
earch11 = ugarchfit(y, spec = spec, solver = "solnp")

residuos_earch11=residuals(earch11)

"""#### Estadísticas Descriptivas de EGARCH(1,1)

Media, Mediana, DT, Mínimo, Máximo, Asimetría, Curtosis, Jarque-Bera y N
"""

y=residuos_earch11

mean(y)

median(y)

sd(y)

min(y)

max(y)

skewness=function(x) {
m3=mean((x-mean(x))^3)
skew=m3/(sd(x)^3)
skew}
skewness(y)

kurtosis=function(x) {
m4=mean((x-mean(x))^4)
kurt=m4/(sd(x)^4)-3 
kurt}
kurtosis(y)

jarque.bera.test(y)

length(y)

serie_earch11=y
plot=qplot(serie_earch11, geom="histogram") 
plot
ggsave(plot,file="hist_earch11.eps")

qqnorm(y)
qqline(y, col = "blue")
ggsave(plot,file="qqplot_earch11.eps")

plot(y)





















"""## 2 Tests de linealidad

### 2.1. BDS Test

No se rechaza la nula (iid).
"""

x=ibmdata$Close
bdsTest(x, m = 15, eps =0.35*sd(ibmdata$Close), title = "BDS Test", description = "BDS Test aplicado al historico de IBM:\n . . H0: xt iid vs H1: xt not iid")

